name: z_components
description: Z_Components is a package that contains a set of standardized components to facilitate, optimize, and accelerate the development of Zellar company's Android / IOS applications.
version: 0.9.23+1
author: Zellar <zellarrh1@gmail.com>
homepage: https://github.com/victortmarques/zcomponents

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^2.0.1
  mask_shifter: ^0.1.0
  cached_network_image: ^2.0.0
  mask_text_input_formatter: ^1.0.2
  pin_code_text_field: ^1.5.0
  cpf_cnpj_validator: ^1.0.5
  flutter_circular_chart: ^0.1.0
  email_validator: '^1.0.0'
  configurable_expansion_tile: ^1.0.0
  http: ^0.12.0+1
  sqflite: ^1.1.6+4
  injector: ^1.0.8
  shared_preferences: ^0.5.6+3
  dio: ^3.0.9
  circular_check_box: ^1.0.1
  intl: ^0.16.0
  meta: ^1.1.8
  path: ^1.6.4
  shimmer: ^1.0.1
  pull_to_refresh: ^1.5.7
  flutter_spinkit: ^4.1.2
  percent_indicator: ^2.1.1+1
  after_init: ^0.1.2
  flutter_webview_plugin: ^0.3.10+1
  uuid: ^2.0.4
  randombytes: ^0.1.1
  after_layout: ^1.0.7+2
  image_picker: ^0.6.3+4
  youtube_player_flutter: ^6.1.0+4
  video_player: ^0.10.8+1
  video_thumbnail: ^0.2.0
  path_provider: ^1.6.5
  chewie: ^0.9.10
  url_launcher: ^5.4.2
  flutter_cache_manager: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.zellar.zcomponents.z_components
    pluginClass: ZComponentsPlugin

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/z.png
    - assets/perfil.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
